import { Inter } from "next/font/google";
import "./globals.css";
import "./prism-dracula.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/4.0.0/github-markdown.min.css"/>
      </head>
      <body className={inter.className +'  container mx-[auto]'}>
        <div className="markdown-body mr-40">{children}</div>
      </body>
    </html>
  );
}
